bundles:
  [
    {
      markers: [
          {
            id: 0,
            corners: [
              [-0.035,  0.035, 0.0],
              [0.035,  0.035, 0.0],
              [0.035,  -0.035, 0.0],
              [-0.035,  -0.035, 0.0]
            ]
          },
          {
            id: 1,
            corners: [
              [0.035,  -0.105, 0.0],
              [0.105,  -0.105, 0.0],
              [0.105,  -0.185, 0.0],
              [0.035,  -0.185, 0.0]
            ]
          }
        ]
    }
  ]


# Marker Notation

# 1          2
# ############
# ############
# ############
# ############
# ############
# 4          3
