bundles:
  [
    {
      markers: [
          {
            id: 0,
            corners: [
              [-0.035,  0.035, 0.0],
              [0.035,  0.035, 0.0],
              [0.035,  -0.035, 0.0],
              [-0.035,  -0.035, 0.0]
            ]
          },
          {
            id: 1,
            corners: [
              [0.035,  -0.105, 0.0],
              [0.105,  -0.105, 0.0],
              [0.105,  -0.185, 0.0],
              [0.035,  -0.185, 0.0]
            ]
          }
        ]
    },
    {
      markers: [
        {
          id: 0,
          corners: [
            [-0.025,  0.025, 0.0],
            [0.025,  0.025, 0.0],
            [0.025,  -0.025, 0.0],
            [-0.025,  -0.025, 0.0]
          ]
        },
        {
          id: 1,
          corners: [
            [0.075,  -0.025, 0.0],
            [0.125,  -0.025, 0.0],
            [0.125,  -0.075, 0.0],
            [0.075,  -0.075, 0.0]
          ]
        },
        {
          id: 2,
          corners: [
            [-0.025,  -0.075, 0.0],
            [0.025,  -0.075, 0.0],
            [0.025,  -0.125, 0.0],
            [-0.025,  -0.125, 0.0]
          ]
        },
        {
          id: 3,
          corners: [
            [0.075,  -0.125, 0.0],
            [0.125,  -0.125, 0.0],
            [0.125,  -0.175, 0.0],
            [0.075,  -0.175, 0.0]
          ]
        }
      ]
    },
    {
      markers: [
        {
          id: 10,
          corners: [
            [-0.035,  0.035, 0.0],
            [0.035,  0.035, 0.0],
            [0.035,  -0.035, 0.0],
            [-0.035,  -0.035, 0.0]
          ]
        },
        {
          id: 2,
          corners: [
            [-0.095,  0.095, 0.0],
            [-0.045,  0.095, 0.0],
            [-0.045,   0.045, 0.0],
            [-0.095,   0.045, 0.0]
          ]
        },
        {
          id: 4,
          corners: [
            [0.045,  0.095, 0.0],
            [0.095,  0.095, 0.0],
            [0.095,  0.045, 0.0],
            [0.045,  0.045, 0.0]
          ]
        }
      ]
    }

  ]


# Marker Notation

# 1          2
# ############
# ############
# ############
# ############
# ############
# 4          3
